#member
/member/inputForm.do=member.action.InputFormAction
/member/inputPro.do=member.action.InputProAction
/member/loginForm.do=member.action.LoginFormAction
/member/loginPro.do=member.action.LoginProAction
/member/logout.do=member.action.LogoutAction
/member/modify.do=member.action.ModifyAction
/member/modifyForm.do=member.action.ModifyFormAction
/member/modifyPro.do=member.action.ModifyProAction
/member/deleteForm.do=member.action.DeleteFormAction
/member/deletePro.do=member.action.DeleteProAction
/member/myDetail.do=member.action.MyDetailAction
#notice
/notice/nlist.do=notice.action.NlistAction
/notice/nwriteForm.do=notice.action.NwriteFormAction
/notice/nwritePro.do=notice.action.NwriteProAction
/notice/ncontent.do=notice.action.NcontentAction
/notice/nupdateForm.do=notice.action.NupdateFormAction
/notice/nupdatePro.do=notice.action.NupdateProAction
/notice/ndeleteForm.do=notice.action.NdeleteFormAction
/notice/ndeletePro.do=notice.action.NdeleteProAction
#product
/product/productList.do=product.action.ProductListAction
/product/productDetail.do=product.action.ProductDetailAction
#order
/order/cartList.do=order.action.CartListAction
/order/cartPro.do=order.action.CartProAction
/order/orderList.do=order.action.OrderListAction
/order/orderPro.do=order.action.OrderProAction
#index
/index/index.do=index.action.IndexAction