INSERT INTO MEMBER (MEMBER_ID, MEMBER_NAME, MEMBER_PW, ACTIVATED) VALUES (1001, 'admin', '$2a$08$lDnHPz7eUkSi6ao14Twuau08mzhWrL4kyZGGU5xfiGALO/Vxd5DOi', 1);
INSERT INTO MEMBER (MEMBER_ID, MEMBER_NAME, MEMBER_PW, ACTIVATED) VALUES (1002, 'user', '$2a$08$UkVvwpULis18S19S5pZFn.YHPZt3oaqHZnDwqbCW9pft6uFtkXKDC', 1);

INSERT INTO AUTHORITY (AUTHORITY_NAME) values ('ROLE_USER');
INSERT INTO AUTHORITY (AUTHORITY_NAME) values ('ROLE_ADMIN');

INSERT INTO USER_AUTHORITY (MEMBER_ID, AUTHORITY_NAME) values (1001, 'ROLE_USER');
INSERT INTO USER_AUTHORITY (MEMBER_ID, AUTHORITY_NAME) values (1001, 'ROLE_ADMIN');
INSERT INTO USER_AUTHORITY (MEMBER_ID, AUTHORITY_NAME) values (1002, 'ROLE_USER');